version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: uncledev
      POSTGRES_PASSWORD: Pyrexer__133
      POSTGRES_DB: goodnature
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

volumes:
  pgdata:
